services:
  mysql:
    image: mysql:8.4
    container_name: ann-mysql
    ports:
      - "3307:3306"
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sework
      MYSQL_USER: sework
      MYSQL_PASSWORD: qwerxjl159357
      MYSQL_ROOT_PASSWORD: qwerxjl159357
    volumes:
      - mysql_data:/var/lib/mysql

  qdrant:
    image: qdrant/qdrant:v1.9.2
    container_name: ann-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    restart: unless-stopped
    environment:
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__GRPC_PORT: 6334
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  mysql_data:
  qdrant_storage:
